### ISSUE TITLE
SIGILL panic

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#12]
Hi there,

We have now a nice randomness beacon using this library at https://github.com/dedis/drand .
Unfortunately, we still have some errors from the bn library as shown below. It appeared one or two times on my laptop but is now appearing everytime on my server (arch-based too). 
In order to reproduce, simply try to launch the docker image from the above link. Maybe try that on a system where bn is *not* installed yet.

Would you have any idea of the cause of this panic ?

Thanks.

Here the log:
```
goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x5634a2d5c3f0, 0xc420045e90, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:131 +0xe8 fp=0xc420045e50 sp=0xc420045e10
github.com/dedis/drand/vendor/github.com/dfinity/go-dfinity-crypto/bls._Cfunc_blsInit(0x600000000, 0x0)
	github.com/dedis/drand/vendor/github.com/dfinity/go-dfinity-crypto/bls/_obj/_cgo_gotypes.go:167 +0x4f fp=0xc420045e90 sp=0xc420045e50
github.com/dedis/drand/vendor/github.com/dfinity/go-dfinity-crypto/bls.Init(0x0, 0x5634a3134660, 0xd)
	/go/src/github.com/dedis/drand/vendor/github.com/dfinity/go-dfinity-crypto/bls/bls.go:16 +0x38 fp=0xc420045ef0 sp=0xc420045e90
github.com/dedis/drand/pbc.NewPairing(0x0, 0x5634a2d465a5)
	/go/src/github.com/dedis/drand/pbc/group.go:76 +0x3a fp=0xc420045f38 sp=0xc420045ef0
github.com/dedis/drand/pbc.NewPairingFp254BNb(0x563400000000)
	/go/src/github.com/dedis/drand/pbc/group.go:85 +0x2c fp=0xc420045f58 sp=0xc420045f38
main.init()
	/go/src/github.com/dedis/drand/keys.go:18 +0xd4 fp=0xc420045f88 sp=0xc420045f58
runtime.main()
	/usr/lib/go/src/runtime/proc.go:173 +0x1d2 fp=0xc420045fe0 sp=0xc420045f88
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420045fe8 sp=0xc420045fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2197 +0x1

rax    0xf
rbx    0x1
rcx    0x8
rdx    0x18
rdi    0x7f373e17a638
rsi    0x0
rbp    0x18
rsp    0x7fff678f97b0
r8     0x5
r9     0x7
r10    0x8
r11    0x7fff678f9b88
r12    0x7f373e17a638
r13    0x7f373e17a2e0
r14    0x28
r15    0x5
rip    0x7f373edb3951
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by nikkolasg** [comment]
It's kinda weird in fact. If I re-build the docker images locally, on my server, it works again. But that should not be required to rebuilt right ?
Erf... I'm still leaving that issue open just to see if you have any thoughts on this, although now I'm not sure if the error is on my side, on yours or on Docker's side lol.
Thanks.

**Comment by herumi** [comment]
What command should I run after `docker pull dedis/drand` for a sample?

**Comment by nikkolasg** [comment]
One stupid example:
```docker run --rm --volume $HOME/.drand/:/root/.drand dedis/drand localhost:6000```
It is supposed to generate a key pair. That fails when using the docker image from dockerhub on my server. If you build the containers yourself with
```
go get github.com/dedis/drand
cd $GOPATH/src/github.com/dedis/drand
docker build -t dedis/drand:bn -f Dockerfile_bn .
docker build -t dedis/drand -f Dockerfile .
```
And run the command again, it worked on my server. Very strange.

**Comment by nikkolasg** [comment]
*updated my first command it was not working sorry*

**Comment by herumi** [comment]
I have run `drand/run_local.sh` on my host PC mistakenly, and it broke my network settings. It took one day to find why I could not access the Internet. Please wait a moment.

**Comment by nikkolasg** [comment]
Oh my. I'm sorry for that. This script creates a docker network and only run some docker containers, it does not touch any personal network configurations. But if you found the issue and think I can fix it or make it safer please fill an issue about it in [drand](https://github.com/dedis/drand) !
Thanks a lot for looking out for this !

**Comment by nikkolasg** [comment]
Just as a reminder that the bug appears even with the `keygen` cmd, so you should be able to launch the docker image without any network directly, bypassing the need for executing the `run_local.sh` script.

**Comment by herumi** [comment]
I ran the following command several times, but I have no error.
What I do try next?

```
>git clone git@github.com:dedis/drand
>cd drand
>git br -v

* master 34685ae Update README.md

>doocker pull dedis/drand

Using default tag: latest
latest: Pulling from dedis/drand
b56ae66c2937: Pull complete
5ff69aeeed93: Pull complete
ede22ffb54eb: Pull complete
8e5902c86cfa: Pull complete
2687e7118a7f: Pull complete
Digest: sha256:1167e9f529514c7b6cda7e1a7e60c8fb4fb95cd2db37ff0ea2b173d397cbec46
Status: Downloaded newer image for dedis/drand:latest

docker run --rm --volume $HOME/.drand/:/root/.drand dedis/drand keygen localhost:6000
drand v0.1-test by nikkolasg @ DEDIS, EPFL
WARNING: this software has NOT received a full audit and must be
used with caution and probably NOT in a production environment.
Generated private key at  /root/.drand/drand_id.private
Generated public key at  /root/.drand/drand_id.public
You can copy paste the following snippet to a common group.toml file:
[[nodes]]
Address = "localhost:6000"
Key = "306c8ad610bbe604b8f179dc3b14c2dffc3eb211f0f943c932b26a9e7fdc1908251e83c2e595436644eb073a9a174ed2d8fc9d2f684048349f0565ba7b01350c"
```

**Comment by herumi** [comment]
What do you use OS/CPU?
I use Ubuntu 16.04.3 LTS/Core(TM) i7-7500U .
Can you use `go build` for the SEGV code, and give me the executable code?

**Comment by nikkolasg** [comment]
Damn, it works for us as well now. My last commit into master made the whole compilation process of bn tied with installation of the golang binary, so I guess it must have changed something for the better since it works well now for me on my server and laptop and for my colleage @Daeinar as well.
I'll try to see if I have time later to try to find back the old binary (the one that was pushed to Dockerhub before the one that is present now; I need to break stuff for that so I won't do that on a Friday !) but in the meantime I'll close this issue since .. well.. it disappeared !
Thanks a lot for checking with me and sorry for your lost connectivity !!
