### ISSUE TITLE
Cannot compile on OpenBSD 6.1

### ISSUE THREAD

**Issue by enzoh** [dfinity/bn#2]
make -C mcl UPDATE_ASM=1 lib/libmcl.a CFLAGS_USER=-std=c++11 MCL_MAX_BIT_SIZE=384
*** Parse error in /home/custodian/workspace/go/src/github.com/dfinity/bn/mcl: Missing dependency operator (common.mk:3)
*** Parse error: Need an operator in 'endif' (common.mk:5)
*** Parse error: Missing dependency operator (common.mk:6)
*** Parse error: Need an operator in 'else' (common.mk:12)
*** Parse error: Need an operator in 'endif' (common.mk:14)
*** Parse error: Missing dependency operator (common.mk:17)
*** Parse error: Need an operator in 'endif' (common.mk:19)
*** Parse error: Missing dependency operator (common.mk:20)
*** Parse error: Need an operator in 'endif' (common.mk:22)
*** Parse error: Missing dependency operator (common.mk:23)
*** Parse error: Need an operator in 'endif' (common.mk:30)
*** Parse error: Missing dependency operator (common.mk:31)
*** Parse error: Need an operator in 'endif' (common.mk:37)
*** Parse error: Missing dependency operator (common.mk:38)
*** Parse error: Need an operator in 'endif' (common.mk:42)
*** Parse error: Missing dependency operator (common.mk:43)
*** Parse error: Need an operator in 'endif' (common.mk:46)
*** Parse error: Missing dependency operator (common.mk:47)
*** Parse error: Need an operator in 'endif' (common.mk:49)
*** Parse error: Missing dependency operator (common.mk:56)
*** Parse error: Missing dependency operator (common.mk:57)
*** Parse error: Need an operator in 'endif' (common.mk:60)
*** Parse error: Need an operator in 'else' (common.mk:61)
*** Parse error: Missing dependency operator (common.mk:63)
*** Parse error: Need an operator in 'else' (common.mk:65)
*** Parse error: Missing dependency operator (common.mk:66)
*** Parse error: Need an operator in 'else' (common.mk:68)
*** Parse error: Need an operator in 'endif' (common.mk:70)
*** Parse error: Need an operator in 'endif' (common.mk:71)
*** Parse error: Missing dependency operator (common.mk:72)
*** Parse error: Missing dependency operator (common.mk:73)
*** Parse error: Need an operator in 'endif' (common.mk:75)
*** Parse error: Need an operator in 'else' (common.mk:76)
*** Parse error: Need an operator in 'endif' (common.mk:78)
*** Parse error: Need an operator in 'endif' (common.mk:79)
*** Parse error: Missing dependency operator (common.mk:86)
*** Parse error: Need an operator in 'endif' (common.mk:88)
*** Parse error: Missing dependency operator (Makefile:8)
*** Parse error: Missing dependency operator (Makefile:11)
*** Parse error: Need an operator in 'endif' (Makefile:13)
*** Parse error: Missing dependency operator (Makefile:14)
*** Parse error: Need an operator in 'endif' (Makefile:16)
*** Parse error: Need an operator in 'endif' (Makefile:17)
*** Parse error: Missing dependency operator (Makefile:20)
*** Parse error: Need an operator in 'endif' (Makefile:22)
*** Parse error: Missing dependency operator (Makefile:23)
*** Parse error: Need an operator in 'endif' (Makefile:25)
*** Parse error: Missing dependency operator (Makefile:40)
*** Parse error: Need an operator in 'else' (Makefile:42)
*** Parse error: Need an operator in 'endif' (Makefile:44)
*** Parse error: Missing dependency operator (Makefile:45)
*** Parse error: Need an operator in 'endif' (Makefile:47)
*** Parse error: Missing dependency operator (Makefile:54)
*** Parse error: Need an operator in 'endif' (Makefile:57)
*** Parse error: Missing dependency operator (Makefile:70)
*** Parse error: Need an operator in 'endif' (Makefile:73)
*** Parse error: Missing dependency operator (Makefile:75)
*** Parse error: Need an operator in 'endif' (Makefile:77)
*** Parse error: Missing dependency operator (Makefile:79)
*** Parse error: Need an operator in 'else' (Makefile:82)
*** Parse error: Need an operator in 'endif' (Makefile:85)
*** Parse error: Missing dependency operator (Makefile:124)
*** Parse error: Need an operator in 'else' (Makefile:127)
*** Parse error: Need an operator in 'endif' (Makefile:129)
*** Parse error: Filename missing from "-include" (Makefile:188)
*** Error 1 in /home/custodian/workspace/go/src/github.com/dfinity/bn (Makefile:6 'mcl/lib/libmcl.a')

**Comment by enzoh** [comment]
Compiling with gmake instead of make gives:

gmake -C mcl UPDATE_ASM=1 lib/libmcl.a CFLAGS_USER=-std=c++11 MCL_MAX_BIT_SIZE=384
gmake[1]: Entering directory '/home/custodian/workspace/go/src/github.com/dfinity/bn/mcl'
g++ -c  -o obj/.o -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith  -I include -I test -I ../xbyak -I ../cybozulib/include -std=c++11 -fomit-frame-pointer -DNDEBUG -Ofast -fPIC -DMCL_MAX_BIT_SIZE=384 -DMCL_USE_LLVM=1
g++: fatal error: no input files
compilation terminated.
gmake[1]: *** [Makefile:106: obj/.o] Error 1
gmake[1]: Leaving directory '/home/custodian/workspace/go/src/github.com/dfinity/bn/mcl'
gmake: *** [Makefile:6: mcl/lib/libmcl.a] Error 2

**Comment by herumi** [comment]
It seems to fail OS detection. How about `gmake -C mcl UPDATE_ASM=1 lib/libmcl.a CFLAGS_USER=-std=c++11 MCL_MAX_BIT_SIZE=384 ARCH=x86_64`?

Could you tell me the values?
* uname -s
* arch

What version of llvm do you use?
If `opt` command has a suffix such as `opt-3.8`, then it is necessary `LLVM_VER=-3.8`, too.

**Comment by enzoh** [comment]
Trying the command you suggested gives a different error:

gmake: Entering directory '/home/custodian/workspace/go/src/github.com/dfinity/bn/mcl'
g++ -o src/gen src/gen.cpp -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith -m64 -I include -I test -I ../xbyak -I ../cybozulib/include -std=c++11 -fomit-frame-pointer -DNDEBUG -Ofast -march=native -fPIC -DMCL_MAX_BIT_SIZE=384 -DMCL_USE_LLVM=1 -O0
/tmp//ccFsGX7I.s: Assembler messages:
/tmp//ccFsGX7I.s:15588: Error: no such instruction: `shlx %eax,%edx,%eax'
gmake: *** [Makefile:132: src/gen] Error 1
gmake: Leaving directory '/home/custodian/workspace/go/src/github.com/dfinity/bn/mcl'

**Comment by enzoh** [comment]
uname -s = OpenBSD
arch = OpenBSD.amd64

**Comment by enzoh** [comment]
custodian@sovereign:bn$ opt --version
LLVM (http://llvm.org/):
  LLVM version 4.0.0
  Optimized build.
  Default target: amd64-unknown-openbsd6.1
  Host CPU: skylake

**Comment by herumi** [comment]
>/tmp//ccFsGX7I.s:15588: Error: no such instruction: `shlx %eax,%edx,%eax'

I think that as(gas) is old. shlx is an instruction supported by Haswell or later cpu.

**Comment by enzoh** [comment]
I'm using a bran new ThinkPad X1 Carbon...
custodian@sovereign:bn$ dmesg | grep CPU  
cpu0: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz, 2712.00 MHz

**Comment by enzoh** [comment]
That's literally what I'm doing right now lol.. I'm installing it from source.

**Comment by enzoh** [comment]
There is infact a version mismatch on my system. It appears this binary was not replaced when I upgraded GCC

**Comment by herumi** [comment]
>arch = OpenBSD.amd64

Thank you for your information.
https://github.com/dfinity/bn/compare/supportOpenBSD is ok?
