### ISSUE TITLE
Makefile not working on Arch

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#5]
Hi there,

When I use the tarball archives, place the .so and .a and .h in my system paths, all works fine.
But I can't make the Makefile to work. When at the top root level I have:
```bash
make -C mcl UPDATE_ASM=1 lib/libmcl.a CFLAGS_USER=-std=c++11 MCL_MAX_BIT_SIZE=384
make[1]: Entering directory '/home/nalos/prog/dfinity/bn/mcl'
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
make[1]: arch: Command not found
g++ -c  -o obj/.o -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith  -I include -I test -I ../xbyak -I ../cybozulib/include -std=c++11 -fomit-frame-pointer -DNDEBUG -Ofast -fPIC -DMCL_MAX_BIT_SIZE=384 -DMCL_USE_LLVM=1
g++: fatal error: no input files
...
```
so, when trying in the `mcl` folder, I have:
```
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
make: arch: Command not found
g++ -c  -o obj/.o -g3 -Wall -Wextra -Wformat=2 -Wcast-qual -Wcast-align -Wwrite-strings -Wfloat-equal -Wpointer-arith  -I include -I test -I ../xbyak -I ../cybozulib/include  -fomit-frame-pointer -DNDEBUG -Ofast -fPIC -DMCL_USE_LLVM=1
g++: fatal error: no input files
compilation terminated.
make: *** [Makefile:106: obj/.o] Error 1
```

Does it work on a vanilla unix system ?

**Comment by herumi** [comment]
arch command is in coreutils(https://www.computerhope.com/unix/uarch.htm), so I think it is basic command. What OS do you use?
Could you try `make ARCH=x86_64`?
Can you use `uname -m`? Then it is better to replace `arch` with `uname -m`.

**Comment by nikkolasg** [comment]
I don't have arch even though I have Archlinux's coreutils but it works fine with `ARCH=x86_64` :)

Another related issue is that I had to change the prefix path with `make install PREFIX=/usr/local/ ARCH=x86_64" so the libraries are recognized locally on my system (instead of linking them when playing with go). I'm not a super expert on these matters, but is there no a relative "default" place where to put the libraries ?
Otherwise, just indicate those commands on the README would also be useful :)

Thanks a lot!

**Comment by nikkolasg** [comment]
Actually I came by the [installation manual](https://github.com/relic-toolkit/relic/wiki/Building#installation) of Relic and it would be super nice to have something similar.
I'm just thinking about the best ways to make the installation for external users of the library a painless step, because this library is getting and gets more and more attentions.
For developpers, I guess it'd be nice to have at least the binaries and headers placed in the os usual folders (most likely `/usr/local`). The best thing would be to have the usual 3 (or two!) command lines instructions such as 
```
./configure
make
make install
``` 
That would already be awesome. The next step after that would be to have an ubuntu/debian & brew package, but that can definitely wait !

**Comment by herumi** [comment]
Fix: use `uname -m` instead of `arch` command.
https://github.com/dfinity/bn/commit/b3f382809b88a078a6411b464e8f5bc84a77a9ba
Fox: change default path from `/workspace/build/cpp/` to `/usr/local/`.
https://github.com/dfinity/bn/commit/877c95d23116efd69c3761b4e3527d557188f572

Is is ok?

**Comment by timohanke** [comment]
@nikkolasg Could you do any of the ubuntu, debian or brew packaging?
I've been thinking about it for a while that we should eventually do it. But nobody got around to do it so far. As you say, it can wait. But the more people we get to use it with the least amount of friction for them the better.

**Comment by herumi** [comment]
@timohanke I have changed the default path of `make install` then I tried to fix crypto/Dockerfile but there is no repository. Where should I fixe it?

**Comment by nikkolasg** [comment]
@timohanke I'm currently quite busy but I feel like we're gonna using this library for other projects too after this one so at one point, it's definitely something that's got to be done. I just don't want to commit for this now ;)

**Comment by nikkolasg** [comment]
@herumi The new makefile is good for me so I'll close this issue for now.
