### ISSUE TITLE
Error with global contexts

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#6]
Hello,

I have problems with the library when concurrency is in place. I raised the issue last time that having a global variable for the "context" will probably a hurdle, and maybe I encouter problems because of this, although I'm not sure yet.

My following piece of [test](https://github.com/dedis/paper_17_dfinity/blob/c44718d194fce41785b5ed1a08d38639b64305ae/protocol/dkg/packets_test.go#L30-L48) fails:
```go
func TestPointMarshalling(t *testing.T) {
        // hexadecimal encoded string from Serialize()
	buff := "7f22c088c2ff348d390bd0975d32e678f1cd0d8b23cc13cd9a6ce50e8dbe4808d5cdd1f12daf039af99edc80a6f62b9e9475dff452cb987e57d2a7026bf0258d"
	decoded, err := hex.DecodeString(buff)
	require.Nil(t, err)

	go TryDecode(t, decoded)
        TryDecode(t, decoded)
}

func TryDecode(t *testing.T, decoded []byte) {
	for i := 0; i < 10; i++ {
		p := pbc.NewPairingFp254BNb()
		g2 := p.G2()
		point := g2.Point()
		require.Nil(t, point.UnmarshalBinary(decoded))
		point.MarshalBinary()
	}
}
```

The errors are coming from the C library such as:
```
*** Error in `/tmp/go-build187739079/github.com/dedis/paper_17_dfinity/protocol/dkg/_test/dkg.test': double free or corruptio
n (fasttop): 0x000000000153cf70 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x72bdd)[0x7f5b9b722bdd]
```
I installed the latest version available a few days ago and I'm running on Arch linux.

Happy to give any additional informations about the problem. I'm not sure how to proceed here...
And YES we need to be able to do operations in parallel :) I believe if I only instantiate one pairing and use the same it works, but it's not something desirable as we launch multiple servers locally in the same process for testing purposes amongst others reasons.

Thanks a lot !

**Comment by herumi** [comment]
`crypto/bls.go:Init` is not thread safe, so I think `p := pbc.NewPairingFp254BNb()` is moved to out of the loop.
https://github.com/dfinity/clarity/blob/master/go/src/dfinity/crypto/bls/bls.go#L19-L28

**Comment by nikkolasg** [comment]
I know that if I move it out of the loop it works but this is only a failing test, the whole DKG implementation have tests that need to run locally, with multiple instance of the pairing and so forth.  is there no "easy" way to make bn thread safe ? 
Otherwise, I also have to use a global variable for that and it's highly likely that it's going to cause trouble in the very near future so I'd avoid that as much as possible. Global variables are evil !

**Comment by herumi** [comment]
mcl has global value because it is designed for an operator overload of C++ without duplicate pointer member to the parameter for each instance of Fp, Fr, Ec, etc.
I'll make safeInit. Please wait a moment.

**Comment by herumi** [comment]
I added `blsInitThreadSafe` at https://github.com/dfinity/bn/commit/dae7c9720a97856019f2e730543768551f846090 .
Please could try it by replacing `blsInit` with `blsInitThreadSafe`?
Which do you use mcl.go or bls.go?

**Comment by nikkolasg** [comment]
Thanks a lot for your quick reaction ! That's great.
I'm using your wrapper in at https://github.com/dfinity/go-dfinity/crypto/bls . If you could push your change upstream to bls that'd be great.
Thanks again.

**Comment by herumi** [comment]
Thank you for your verification. I update bn and blsInit is thread safe, then it is unnecessary to modify go code. https://github.com/dfinity/bn/commit/c7c2294d4ada33cfdbc6b0de80f0afa9ac9a193f

**Comment by nikkolasg** [comment]
Great, it seems to work well, thank you :)
