### ISSUE TITLE
Dynamic linking: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by nikkolasg** [dfinity/bn#9]
Hi,
I'm trying to use the library on ubuntu 14.04 (no access to 16.04). There seems to be a mismatch between the libstdc++ version installed and the one libbls384.so expects ? 
Is it possible to make it work on 14.04 ?

I tried many solutions like:
```bash
 sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
``` 
from [AskUbuntu](https://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error) but nothing really works...

Thanks

**Comment by herumi** [comment]
I'm sorry too late response because I missed this notification.

I think that the best way is to rebuild the the library on ubuntu 14.
Is it difficult?

**Comment by nikkolasg** [comment]
Yep, seems like it. I'm trying to to compile on 14.04 ;)
